[window.padding]
x = 6

[font]
normal = { family = "Fira Code Retina", style = "Regular" }
size = 12.7

# Theme for Alacritty
[colors.primary]
background = "#353c45"
foreground = "#d8dee9"

[colors.cursor]
cursor = "#d8dee9"
text = "#ffffff"

[colors.selection]
background = "#d8dee9"
text = "#353c45"

[colors.normal]
black = "#000000"
red = "#f92672"
green = "#a6e22e"
yellow = "#f4bf75"
blue = "#3d90e3"
magenta = "#ae81ff"
cyan = "#3d90e3"
white = "#f8f8f2"

[colors.bright]
black = "#555555"
red = "#f92672"
green = "#a6e22e"
yellow = "#ffd866"
blue = "#3d90e3"
magenta = "#6679cc"
cyan = "#9afbff"
white = "#ffffff"