# Enable mouse support
set -g mouse on

# Keyboard bindings
bind -n C-t new-window                    # Ctrl+t: Open a new window
bind -n C-p resize-pane -Z                # Ctrl+p: Toggle pane zoom
bind -n C-h split-window -h               # Ctrl+h: Horizontal split
bind -n C-v split-window -v               # Ctrl+v: Vertical split
bind -n F2 previous-window                # F2: Move to the previous window
bind -n F3 next-window                    # F3: Move to the next window

# Status bar configuration
set-option -g status-position top         # Position the status bar at the top of the screen
set-option -g status-left-length 30       # Set the length of the left status bar
set-option -g status-right-length 150     # Set the length of the right status bar

# Status bar style
set-option -g status-bg '#ff9800'         # Background color of the status bar
set-option -g status-left "\
#[fg=colour246,bg=colour237] \uf251 Focus #[fg=colour248,bg=#ff9800] "  # Left status configuration

# Right status configuration, including scripts and system info
set-option -g status-right " \
#(~/Scripts/vpnIP_VM.sh)  #(whoami)@#(hostname) \
#[fg=colour246, bg=colour237] %b %d '%y \
#[fg=colour109] %l:%M %p \
#[fg=colour248, bg=colour239]"
